### ISSUE TITLE
Lack of RSA-SHA1 support

### ISSUE THREAD

**Issue by Artur2** [gsuitedevs/apps-script-oauth1#30]
HI guys!

Have a trouble with authenticating w/ JIRA REST API, because they support only RSA-SHA1(not SHA2).
Will there be support in the future of RSA-SHA1 ?

**Comment by erickoledadevrel** [comment]
Unfortunately Apps Script currently doesn't provide the ability to compute RSA-SHA1 hashes (only RSA-SHA256). We would need to add support to the underlying platform before the library could support it.

**Comment by Artur2** [comment]
@erickoledadevrel Thanks for reply!
We'll wait.

**Comment by machinefriendly** [comment]
FYI, RSA-SHA1 is support by an update on 8/20, see [here](https://developers.google.com/apps-script/reference/utilities/utilities)
