### ISSUE TITLE
Can I pass Basic Auth of request url ?

### ISSUE THREAD

**Issue by yuonoda** [gsuitedevs/apps-script-oauth1#37]
Hi, 

thank you for your providing such good tool.

I'm now trying to use this for Wordpress Rest API.
But my website is in staging environment, so locked by Basic Auth.

Is there any good way to pass through Basic Auth to get request token.

Thanks!

**Comment by erickoledadevrel** [comment]
I haven't tried it, but you may be able to encode the the basic authorization in the URL:

    https://username:password@domain.com

If that doesn't work, you'd need to update the library to be able to set authorization headers for that request. This is the area of the code where the request is made:

https://github.com/googlesamples/apps-script-oauth1/blob/master/src/Service.gs#L332

**Comment by yuonoda** [comment]
Thank you for your replay!

I've already tried that url incluging username and passsword. But it doesn't work..

I will try to modify your suggested area on the library !

**Comment by erickoledadevrel** [comment]
@yuonoda - Did you have success modifying the library? Anything that can be contributed back to the library?

**Comment by yuonoda** [comment]
@erickoledadevrel Sorry, I didn't modify the library because I used it on an environment without Basic Auth.
