### ISSUE TITLE
OAuth1 not working in Chrome V8 Engine

### ISSUE THREAD

**Issue by Lolidroid** [gsuitedevs/apps-script-oauth1#48]
Hello,

When using the new Apps Script runtime (Google Chrome V8), the library does not work anymore.

For example: 

```javascript
var CONSUMER_KEY = '...';
var CONSUMER_SECRET = '...';

/**
 * Authorizes and makes a request to the Twitter API.
 */
function run() {
  var service = getService();
  if (service.hasAccess()) {  // Error occured!
    Logger.log('Authorized.');
  } 
} 

function getService() {
  return OAuth1.createService('Twitter')
      .setAccessTokenUrl('https://api.twitter.com/oauth/access_token')
      .setRequestTokenUrl('https://api.twitter.com/oauth/request_token')
      .setAuthorizationUrl('https://api.twitter.com/oauth/authorize')
      .setConsumerKey(CONSUMER_KEY)
      .setConsumerSecret(CONSUMER_SECRET)
      .setPropertyStore(PropertiesService.getScriptProperties());
}
```

I got this error :
```
Property store is required.
    at [unknown function](OAuth1:1058:7)
    at validate_(OAuth1:1055:23)
    at Service_.getToken_(OAuth1:625:3)
    at Service_.hasAccess(OAuth1:409:20)
    at run(Code:10:15)
```

I have found _.isEmpty() returns true when ScriptPropertyStore(has only a non-enumerable property).

https://github.com/gsuitedevs/apps-script-oauth1/blob/d804872cac7ee5e062d39e1060733c472f209b9f/src/Utilities.gs#L58

Thank your for your support !

**Comment by erickoledadevrel** [comment]
Thanks for reporting this! it looks like the methods I was using from Underscore.js aren't working correctly under the v8 engine. Rather than upgrade the library, I've decided to just remove it as a dependency, which we did in the OAuth2 library some time ago. I'll be sending our a PR soon.
