### ISSUE TITLE
There's a bug in OAuth.prototype.getParameterString -- Edit: Twitter / X Ads API is weird as hell

### ISSUE THREAD

**Issue by MonkeyHenry** [gsuitedevs/apps-script-oauth1#79]
I spent a long time trying to figure out why, despite using the exact same credentials for all my X Ads API endpoints, I was successfully hitting some endpoints while being told that I was unauthorised for others, even though everything works perfectly fine with twurl and Postman.  

The problem lies here: 

```
  OAuth.prototype.getBaseString = function(request, oauth_data) {
    return request.method.toUpperCase() + '&' + this.percentEncode(this.getBaseUrl(request.url)) + '&' + this.percentEncode(this.getParameterString(request, oauth_data));
  };
 ```
 
 and here: 
 
 ```
  OAuth.prototype.getParameterString = function(request, oauth_data) {
    var base_string_data = this.sortObject(this.percentEncodeData(this.mergeObject(oauth_data, this.mergeObject(request.data, this.deParamUrl(request.url)))));

    var data_str = '';

    //base_string_data to string
    for(var key in base_string_data) {
      data_str += key + '=' + base_string_data[key] + '&';
    }

    //remove the last character
    data_str = data_str.substr(0, data_str.length - 1);
    return data_str;
  };
  ```
  
As you can see, parameters are being encoded twice. This is a problem when you have parameters with special characters in them, such as colons in datetimes. 

Remove `this.percentEncodeData()` from the `getParameterString` function and the bug is fixed.

**Comment by vinay-google** [comment]
Would you be able to send a pull request for this change? I'll be happy to merge it once it's ready. Thanks!

**Comment by MonkeyHenry** [comment]
@vinay-google I tried to make a PR before making this issue, but when I tried pushing my branch, I was told:

`remote: Permission to googleworkspace/apps-script-oauth1.git denied to MonkeyHenry.
fatal: unable to access 'https://github.com/googleworkspace/apps-script-oauth1.git/': The requested URL returned error: 403`


Edit: I realised just now reading the CONTRIBUTING.md file that I was supposed to sign an agreement at https://cla.developers.google.com/clas. I did so just now, but still getting the same permission denied error. Do I have to wait a bit?

**Comment by MonkeyHenry** [comment]
@vinay-google By the way, while this fixes the problems for one of my endpoints, I'm still having problems with a different endpoint, again being told I'm unauthorised even though everything works fine on twurl and Postman. I'm looking for a potential separate bug in this library, but I'm currently at a loss. 

The only difference with this currently failing endpoint is that it's a POST request rather than a GET request. Maybe also something to do with the fact that some of my parameters have commas in them, though I don't see why that should affect anything. Got any ideas? 

Request data before signing: 
`{"end_time":"2024-08-31T15:00:00Z","entity":"LINE_ITEM","entity_ids":"foobar1,foobar2,foobar3","granularity":"DAY","metric_groups":"ENGAGEMENT,BILLING","placement":"ALL_ON_TWITTER","start_time":"2024-07-31T15:00:00Z"}`

**Comment by MonkeyHenry** [comment]
You know what, I don't even know anymore. None of this makes any sense to me. 

https://lti.tools/oauth/

According to this, parameters **_are supposed to be_** encoded twice in the signature base string. 

But with X Ads API, it doesn't like it when colons in `start_time` and `end_time` (e.g. `2024-07-31T15:00:00Z`) are encoded twice (it only works if I encode it once), but it is expecting other parameters to be encoded twice (e.g. `metric_groups=ENGAGEMENT,BILLING` -> the comma should be encoded twice for it to work, not once).

If this is an X Ads API issue, then I have no idea why everything is working flawlessly with Postman, and I have to jump through hoops to get it to work with my GAS. 

I have absolutely no clue what's going on but I'm just going to patch the library on my environment to work for my specific use case and be done with it.
